[
  {
    "csIntegSchemeCode": "string",
    "csCountry": "string",
    "csStaffNumber": "string",
    "csFamilyCode": "string",
    "csIntegCatCode": "string",
    "csMemType": "string",
    "csMemStatus": 0,
    "csSurname": "string",
    "csFirstName": "string",
    "csSecondName": "string",
    "csOtherNames": "string",
    "csIdNumber": "string",
    "csDob": "2025-12-01",
    "csGender": "string",
    "csJoinDate": "2025-12-01",
    "csNhifNumber": "string",
    "csSchemeStartDate": "2025-12-01",
    "csSchemeEndDate": "2025-12-01",
    "csAddedBy": "string",
    "csBatchNo": "string",
    "csRoamingCountries": "string",
    "csPhoneNumber1": "string",
    "csPhoneNumber2": "string",
    "csWorkBranch": "string",
    "csOfficeBranch": "string",
    "csIsVip": "string",
    "csVipMsg": "string",
    "csNextofKin": "string",
    "csKinEmail": "string",
    "csEmployerName": "string",
    "csEmployerAddress": "string",
    "csEmployerWorktel": "string",
    "csEmployerDepartment": "string",
    "csIntegMemberNumber": "string",
    "csIsReprint": "string",
    "statusMessage": "string"
  }
]