# Generated by Django 5.2.8 on 2025-11-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StagedCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clnCode', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=255)),
                ('clnPolCode', models.CharField(blank=True, max_length=50, null=True)),
                ('anniv', models.IntegerField(blank=True, null=True)),
                ('invoicePt', models.CharField(blank=True, max_length=255, null=True)),
                ('invContactEmail', models.CharField(blank=True, max_length=255, null=True)),
                ('invPtcontactTel', models.CharField(blank=True, max_length=50, null=True)),
                ('polTypeId', models.CharField(blank=True, max_length=50, null=True)),
                ('userId', models.CharField(blank=True, max_length=50, null=True)),
                ('clnPolType', models.CharField(blank=True, max_length=50, null=True)),
                ('policyNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('statusReason', models.CharField(default='NULL', max_length=50)),
                ('cancelled', models.BooleanField(blank=True, null=True)),
                ('countryCode', models.CharField(default='KE', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
            ],
        ),
    ]
