# Generated by Django 5.2.8 on 2025-11-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StagedCorporate',
            new_name='Corporate',
        ),
    ]
