# Generated by Django 5.2.8 on 2025-11-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_rename_stagedcorporate_corporate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catDesc', models.CharField(max_length=255)),
                ('userId', models.CharField(max_length=100)),
                ('clnCatCode', models.CharField(max_length=50)),
                ('clnPolCode', models.CharField(max_length=50)),
                ('customerid', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Benefit Category Payload',
                'verbose_name_plural': 'Benefit Category Payloads',
                'db_table': 'benefit_category_payload',
            },
        ),
    ]
