# Generated by Django 5.2.8 on 2025-11-27 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0003_benefitcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitcategory',
            name='idx',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
