# Generated by Django 5.2.8 on 2025-11-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0004_benefitcategory_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitcategory',
            name='idx',
            field=models.IntegerField(default=0),
        ),
    ]
