# Generated by Django 5.2.8 on 2025-11-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0005_alter_benefitcategory_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(default=0)),
                ('clnPolCode', models.CharField(max_length=50)),
                ('CatCode', models.CharField(max_length=50)),
                ('benTypeId', models.CharField(blank=True, max_length=50, null=True)),
                ('subLimitAmt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('serviceType', models.CharField(max_length=50)),
                ('clnBenCode', models.CharField(max_length=50)),
                ('benefitDesc', models.CharField(blank=True, max_length=255, null=True)),
                ('benLinked2Tqcode', models.CharField(blank=True, max_length=50, null=True)),
                ('memAssignedBenefit', models.CharField(blank=True, max_length=100, null=True)),
                ('Countrycode', models.CharField(default='KE', max_length=5)),
                ('customerid', models.CharField(default='xyz', max_length=100)),
                ('userId', models.CharField(default='msamuel', max_length=100)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
