# Generated by Django 5.2.8 on 2025-12-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0006_benefit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefit',
            old_name='CatCode',
            new_name='catCode',
        ),
    ]
