"""
Django settings for healthcare_hub project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ii74!4@@vu3$j54$z%ynzh#(l^bce@ugbbv896ba^%!=j_c=il'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.0.135","92.168.0.135:8080"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'retail_members',
    'smart',
    'engine',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'healthcare_hub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'healthcare_hub.wsgi.application'




DATABASES = {
    
        'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'localdb',
        'USER': 'smart_user',
        'PASSWORD': 'SmartPass123!',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    
    },
    'external_mssql': {
        'ENGINE': 'mssql',
        'NAME': 'healthcaredb',
        'USER': 'app_user',
        # 'PASSWORD': 'M@dison@!0',
        'PASSWORD': 'H@1sDb_22',
        'HOST': '192.168.0.160',  # IP of the SQL Server
        'PORT': '1433',  
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes',
        },
    }
    #  'external_mssql': {
    #     'ENGINE': 'mssql',
    #     'NAME': 'healthcaredb',
    #     'USER': 'app_user',
    #     'PASSWORD': 'M@dison@!0',
    #     'HOST': '192.168.0.110',  # IP of the SQL Server
    #     'PORT': '1433',  
    #     'OPTIONS': {
    #         'driver': 'ODBC Driver 18 for SQL Server',
    #         'extra_params': 'TrustServerCertificate=yes',
    #     },
    # }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'samuel.mwangangi@madison.co.ke'
# EMAIL_HOST_PASSWORD = '#Madison2025'
EMAIL_HOST_USER = 'haisnotifications@madison.co.ke'
EMAIL_HOST_PASSWORD = 'N!271111535161oz'


# settings.py
# SMART_CLIENT_ID = "014201579620236822568101255"
# SMART_CLIENT_SECRET = "UcvBlvJTKBggyppZzCJ97oGxJcw"
# SMART_GRANT_TYPE = "client_credentials"
# SMART_CUSTOMER_ID = "482646589923456863549665"

SMART_CLIENT_ID = "838931be-2921-47e2-a00e-356b833dcec9"
SMART_CLIENT_SECRET = "K13nz2aJMEME1Rjxbvv8A6tCKZg"
SMART_GRANT_TYPE = "client_credentials"
# SMART_CUSTOMER_ID = "482646589923456863549665"
SMART_CUSTOMER_ID="MADC4C23E75B49A1820A604CBE8EQAKE"
SMART_API_URL = "https://data.smartapplicationsgroup.com/api/v2/integqa/members"
SMART_SCHEMES_API_URL = "https://data.smartapplicationsgroup.com/api/v2/integqa/schemes"
SMART_TOKEN_URL = "https://data.smartapplicationsgroup.com/auth/integ-clients/oauth/token"
SMART_BENEFITS_API_URL="https://data.smartapplicationsgroup.com/api/v2/integqa/bulk/benefits"
# https://data.smartapplicationsgroup.com/auth/integ-clients/oauth


HAIS_API_BASE_URL = "http://192.168.100.164/aar/app/members/"
HAIS_CONSUMER_KEY = "mwambeyu.jnr@gmail.com"
HAIS_CONSUMER_SECRET = "smart2020"
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000

COUNTRY_CODE = "KE"
POLICY_CURRENCY_ID = "KES"
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = "Africa/Nairobi"
